accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"

urlpatterns = [
    path("token-register/<str:tk>/", views.token_register, name="token_register"),
    path("token-register/<str:tk>/revoke/", views.revoke_token, name="revoke_token"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout")
]

courses/urls.py
from django.shortcuts import redirect
from django.urls import path

from courses.views import (
    GroupsView,
    delete_teacher,
    group,
    courses,
    edit_course,
    index,
    move_student,
    register_student,
    student_view,
    students_view,
    take_attendance,
    teacher,
    teachers,
)

app_name: str = "courses"

urlpatterns = [
    path("", lambda request: redirect("courses:dashboard"), name="index"),
    path("dashboard/", index, name="dashboard"),
    path("groups/", GroupsView.as_view(), name="groups"),
    path("groups/<int:assign_id>/", group, name="group"),
    path("groups/<int:assign_id>/attendance/", take_attendance, name="attendance"),
    path("courses/", courses, name="courses"),
    path("courses/<int:course_id>/", edit_course, name="course"),
    # teacher related
    path("teachers/", teachers, name="teachers"),
    path("teachers/<uuid:teacher_id>/", teacher, name="teacher"),
    path("teachers/<uuid:teacher_id>/delete/", delete_teacher, name="delete_teacher"),
    # student related
    path("register/", register_student, name="register_student"),
    path("students/", students_view, name="students"),
    path("students/<uuid:student_id>/", student_view, name="student"),
    path(
        "students/<uuid:student_id>/move/<int:class_id>/",
        move_student,
        name="move_student",
    ),
]

main/urls.py
from typing import List

from django.shortcuts import redirect
from django.urls import path

from main.views import (
    GroupsView,
    delete_teacher,
    group,
    index,
    move_student,
    register_student,
    students_view,
    take_attendance,
    teacher,
    teachers,
    student_view,
)

app_name: str = "main"

urlpatterns: List = [
    path("", lambda request: redirect("main:dashboard"), name="dashboard"),
    path("dashboard/", index, name="dashboard"),
    path("groups/", GroupsView.as_view(), name="groups"),
    path("groups/<int:assign_id>/", group, name="group"),
    path("groups/<int:assign_id>/attendance/", take_attendance, name="attendance"),
    # teacher related
    path("teachers/", teachers, name="teachers"),
    path("teachers/<uuid:teacher_id>/", teacher, name="teacher"),
    path("teachers/<int:teacher_id>/delete/", delete_teacher, name="delete_teacher"),
    # student related
    path("register/", register_student, name="register_student"),
    path("students/", students_view, name="students"),
    path("students/<uuid:student_id>/", student_view, name="student"),
    path(
        "students/<uuid:student_id>/move/<int:class_id>/",
        move_student,
        name="move_student",
    ),
]

nano_crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("courses.urls", namespace="courses")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),
    path("__debug__", include("debug_toolbar.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
import uuid
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from core.models import DeptMixin, UUIDMixin
TOKEN_EXPIRE = getattr(
    settings, "REGISTRATION_TOKEN_EXPIRATION_DURATION", timezone.timedelta(weeks=1)
)


class CustomUser(AbstractUser):
    USER_TYPES = (
        ("chef", "Chef of Department"),
        ("teacher", "Teacher"),
    )
    dept = models.ForeignKey(
        "core.Dept", on_delete=models.CASCADE, blank=True, null=True
    )
    user_type = models.CharField(
        max_length=10, choices=USER_TYPES, blank=True, null=True
    )

    @property
    def is_chef(self):
        return self.user_type == "chef"

    @property
    def is_teacher(self):
        return self.user_type == "teacher"


class Chef(UUIDMixin):
    full_name = models.CharField(max_length=254)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.full_name


class Teacher(DeptMixin, UUIDMixin):
    WORKING_DAYS_CHOICES = (
        ("workingdays", "ish kunlari"),
        ("everyotherday", "kun oralab"),
    )
    full_name = models.CharField(max_length=100)
    working_days = models.CharField(max_length=254, choices=WORKING_DAYS_CHOICES)
    working_time = models.CharField(max_length=254)
    courses = models.ManyToManyField("core.Course", blank=True)
    address = models.CharField(max_length=254, default="Andijon")
    phone_numbers = models.CharField(max_length=254, default="None")

    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, blank=True, null=True
    )

    def __str__(self):
        return self.full_name


class RegisterToken(UUIDMixin, DeptMixin):
    token = models.CharField(max_length=32)
    teacher = models.OneToOneField("Teacher", on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    valid_until = models.DateTimeField(blank=True, null=True)

    def is_valid(self) -> bool:
        expire_duration = TOKEN_EXPIRE
        now = timezone.now()
        if self.valid_until:
            is_not_expired = (
                self.valid_until >= now and (self.valid_until - now) <= expire_duration
            )

            # Check if the token is associated with a teacher
            has_teacher = self.teacher.user is not None
            return is_not_expired and not has_teacher
        return False


@receiver(post_save, sender=CustomUser)
def chef_create(instance: CustomUser, created: bool, **kwargs):
    if created:
        user_type = instance.user_type
        if user_type == "chef" and hasattr(instance, "dept"):
            Chef.objects.create(full_name=instance.first_name, user=instance)


@receiver(post_save, sender=RegisterToken)
def update_validation(instance: RegisterToken, created, **kwargs):
    if created:
        instance.valid_until = TOKEN_EXPIRE + timezone.datetime.now()
        instance.save()

courses/models.py
from django.db import models

from core.constants import time_slots, DAYS_OF_WEEK
from core.models import UUIDMixin, DeptMixin


class Class(DeptMixin):
    name = models.CharField(max_length=100)
    day = models.CharField(max_length=254)

    class Meta:
        verbose_name_plural: str = "classes"

    def __str__(self):
        return self.name


class Assign(models.Model):
    class_id = models.ForeignKey("Class", on_delete=models.CASCADE)
    course = models.ForeignKey("core.Course", on_delete=models.CASCADE)
    teacher = models.ForeignKey("accounts.Teacher", on_delete=models.CASCADE)
    period = models.CharField(max_length=50, choices=time_slots, default="8:00 - 9:30")
    day = models.CharField(max_length=50, default='["Monday", "Wednesday", "Friday"]')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (("course", "class_id", "teacher"),)

    def get_monthly_attendance(self, year, month):
        attendance_data = (
            AttendanceClass.objects.filter(
                date__year=year,
                date__month=month,
                assign=self,
            )
        )

        return attendance_data

    def __str__(self):
        cl = self.class_id
        te = self.teacher
        return "%s : %s" % (te.full_name, cl)


class AttendanceClass(models.Model):
    assign = models.ForeignKey("Assign", on_delete=models.CASCADE)
    date = models.DateField()

    class Meta:
        verbose_name: str = "Attendance Session"
        verbose_name_plural: str = "Attendance Sessions"

    def __str__(self) -> str:
        return str(self.date)

class Student(UUIDMixin):
    CONDITION_CHOICES = (
        ("normal", "normal"),
        ("contract", "Kontrakt"),
        ("free", "Free"),
    )
    full_name = models.CharField(max_length=100)
    groups = models.ManyToManyField("Class", blank=True)
    course = models.ForeignKey("core.Course", on_delete=models.CASCADE)
    address = models.TextField(max_length=254, default="Uzbekistan")
    coins = models.IntegerField(default=0)
    phone_numbers = models.CharField(max_length=254)
    condition = models.CharField(
        choices=CONDITION_CHOICES,
        default="normal",
        max_length=10,
    )

    def __str__(self):
        return self.full_name + " ||  " +  str(self.groups.first())
    def get_attendance_on_day(self, day):
        try:
            attendance = self.attendance_set.get(date=day) # type: ignore
            return attendance
        except Attendance.DoesNotExist:
            return None

class Attendance(models.Model):
    student = models.ForeignKey("Student", on_delete=models.CASCADE)
    is_present = models.BooleanField(default=False)
    attendance_class = models.ForeignKey("AttendanceClass", on_delete=models.CASCADE)
    date = models.DateField()
    updated_at: models.DateTimeField = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.student} - {self.attendance_class}"

courses/forms.py
from django import forms

from core.constants import DEFAULT_INPUT_ATTRS, DAYS_OF_WEEK, time_slots
from accounts.models import Teacher
from core.models import Course, Dept
from courses.models import Student

class CreateCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        exclude = ["dept"]
        widgets = {
            "name": forms.TextInput(attrs=DEFAULT_INPUT_ATTRS),
            "shortname": forms.TextInput(attrs=DEFAULT_INPUT_ATTRS),
            "price": forms.NumberInput(attrs=DEFAULT_INPUT_ATTRS),
        }


class CreateClassForm(forms.Form):
    def __init__(self, *args, dept, **kwargs):
        super().__init__(*args, **kwargs)  # type: ignore
        if dept:
            self.fields["teacher"] = forms.ChoiceField(
                choices=Teacher.objects.filter(dept=dept).values_list("id", "full_name")
            )
            self.fields["course"] = forms.ChoiceField(
                choices=Course.objects.filter(dept=dept).values_list("id", "name"),
            )

    name = forms.CharField(
        max_length=254, widget=forms.TextInput(attrs=DEFAULT_INPUT_ATTRS)
    )
    day = forms.MultipleChoiceField(
        choices=DAYS_OF_WEEK,
        initial=["Monday", "Wednesday", "Friday"],
    )
    time = forms.ChoiceField(choices=time_slots)
    percentage = forms.IntegerField(widget=forms.NumberInput(attrs=DEFAULT_INPUT_ATTRS))


class RegisterStudentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        teacher: Teacher | None = kwargs.pop("teacher", None)
        dept: Dept | None = kwargs.pop("dept", None)
        super().__init__(*args, **kwargs)
        if teacher:
            self.fields["course"].queryset = Course.objects.filter(dept=teacher.dept)
        elif dept:
            self.fields["course"].queryset = Course.objects.filter(dept=dept)

    class Meta:
        model = Student
        fields = [
            "full_name",
            "address",
            "phone_numbers",
            "course",
            "condition",
            "groups"
        ]
        widgets = {
            "full_name": forms.TextInput(
                attrs={**DEFAULT_INPUT_ATTRS, "placeholder": "Ismi", "required": True}
            ),
            "address": forms.TextInput(
                attrs={
                    **DEFAULT_INPUT_ATTRS,
                    "placeholder": "Manzili",
                    "required": True,
                }
            ),
            "phone_numbers": forms.TextInput(
                attrs={
                    **DEFAULT_INPUT_ATTRS,
                    "placeholder": "Telefon raqamlari",
                    "required": True,
                }
            ),
            "course": forms.Select(
                attrs={
                    **DEFAULT_INPUT_ATTRS,
                    "placeholder": "Yo'nalishi",
                    "required": True,
                }
            ),
        }

templates/courses/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="{% static 'assets/css/uiverse.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/choices.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <script
      defer
      src="{% static 'assets/js/bootstrap.bundle.min.js' %}"
    ></script>
    <script defer src="{% static 'assets/js/choices.min.js' %}"></script>
    <style>
      ::-webkit-scrollbar {
        width: 8px; /* Set the width of the scrollbar */
      }

      /* Style the track area of the scrollbar */
      ::-webkit-scrollbar-track {
        background-color: #f1f1f1; /* Background color of the track */
      }

      /* Style the thumb of the scrollbar */
      ::-webkit-scrollbar-thumb {
        background-color: #888; /* Color of the thumb */
        border-radius: 4px; /* Rounded corners for the thumb */
      }

      /* Style the thumb on hover */
      ::-webkit-scrollbar-thumb:hover {
        background-color: #555; /* Color of the thumb on hover */
      }
      .required-field label::after {
        content: "*";
        color: var(--bs-red);
        font-weight: bold;
      }
    </style>
  </head>
  <title>{% block title %} {% endblock %}</title>
  <body>
    <div class="container-fluid">
      <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
          <div
            class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
          >
            <a
              href="/"
              class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none"
            >
              <span class="fs-5 d-none d-sm-inline">
                NANO {% comment %} {%if request.user.teacher %}{{
                request.user.teacher.dept.name}} {% elif request.user.chef %} {{
                request.user.chef.dept.name}} {% else %}Admin{%endif%}</span
              >
              {% endcomment %}
            </a>
            <ul
              class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
              id="menu"
            >
              <li>
                <a href="{% url 'courses:dashboard' %}" class="nav-link px-0">
                  <i class="fs-4 bi-people"></i>
                  <span class="ms-1 d-none d-sm-inline">Hisobot</span>
                </a>
              </li>
              <li>
                <a href="{% url 'courses:groups' %}" class="nav-link px-0">
                  <i class="fs-4 bi-speedometer2"></i>
                  <span class="ms-1 d-none d-sm-inline">Guruhlar</span>
                </a>
              </li>
              {% if request.user.user_type == "chef" %}
              <li>
                <a href="{% url 'courses:teachers' %}" class="nav-link px-0">
                  <i class="fs-4 bi-table"></i>
                  <span class="ms-1 d-none d-sm-inline">O'qituvchilar</span></a
                >
              </li>
              <li>
                <a href="{% url 'courses:courses' %}" class="nav-link px-0">
                  <i class="fs-4 bi-table"></i>
                  <span class="ms-1 d-none d-sm-inline">Kurslar</span></a
                >
              </li>
              {% endif %}
              <li>
                <a
                  href="{% url 'courses:register_student' %}"
                  class="nav-link px-0"
                >
                  <i class="fs-4 bi-table"></i>
                  <span class="ms-1 d-none d-sm-inline"
                    >Ro'yxatga olish</span
                  ></a
                >
              </li>
            </ul>
            <hr />
            <div class="dropdown pb-4">
              <a
                class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                id="dropdownUser1"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <span class="d-none d-sm-inline mx-1"
                  >{{ request.user.username }}</span
                >
                <span
                  class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
                >
                  {{ request.user.user_type}}
                </span>
              </a>
              <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                <li>
                  <a class="dropdown-item" href="{% url 'accounts:logout' %}"
                    >Sign out</a
                  >
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col">{% block content %} {% endblock content %}</div>
      </div>
    </div>
  </body>
  {% block script %} {% endblock script %}
</html>

templates/courses/groups.html
{% extends "./base.html" %} {% block content %}
<div class="container py-3" style="height: 100vh; overflow: auto">
  <div class="row align-items-center">
    {% if messages %} {% for message in messages %}
    <div
      class="alert alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{%elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}success{% endif %} alert-dismissible fade show"
      role="alert"
    >
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endfor %} {% endif %} {% for assign in assign_objects %}
    <div class="col-lg-3 col-md-4 col-sm-6">
      <div class="card border-success mb-3" style="max-width: 18rem">
        <div class="card-header bg-transparent border-success">
          {{ assign.day|parse:"0" }}, {{ assign.period }}
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ assign.class_id.name }}</h5>
          <p class="card-text">
            <b>Yo'nalish: </b>
            <span
              ><a href="{% url 'courses:course' assign.course.id %}"
                >{{ assign.course.name}}</a
              ></span
            >
            <br />
            <b>O'qituvchi: </b>
            <span><a href="{% url 'courses:teacher' assign.teacher.id %}">{{ assign.teacher.full_name }}</a></span>
          </p>
        </div>
        <div class="card-footer bg-transparent border-success">
          <a
            href="{% url 'courses:group' assign.id %}"
            class="btn btn-outline-primary"
            >Batafsil
          </a>
        </div>
      </div>
    </div>
    {% endfor%} {% if request.user.user_type == "chef" %}
    <div class="col-lg-3 col-md-4 col-sm-6">
      <button
        type="button"
        class="btn btn-outline-secondary"
        data-bs-toggle="modal"
        data-bs-target="#addGroupModal"
      >
        <div
          class="d-flex justify-content-center align-items-center flex-column"
        >
          <span class="plus-icon" style="font-size: 50px">+</span>
          Guruh yaratish
        </div>
      </button>
    </div>
    {% endif %}
  </div>
</div>

<div
  class="modal fade"
  id="addGroupModal"
  tabindex="-1"
  aria-labelledby="addGroupModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="addGroupModalLabel">Guruh qo'shish</h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form action="" method="post">{% csrf_token %} {{ form }}</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Bekor qilish
        </button>
        <button
          type="button"
          class="btn btn-primary"
          onclick="document.forms[0].submit()"
        >
          Yaratish
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock content %} {% block script %}
<script>
  document.addEventListener("DOMContentLoaded", () => {
    const configs = [
      {},
      {},
      {
        noChoicesText:
          'No choices to choose from <a href="#">Create a new course</a>',
      },
    ];
    const selector = document
      .querySelectorAll("select")
      .forEach((select, index) => {
        const choices = new Choices(select, configs[index]);
      });
  });
</script>
{% endblock %}

templates/courses/student.html
{% extends "./base.html" %} {% block title %} Student - {{ student.full_name }}
{% endblock title %} {% block content %}
<div class="container py-3" style="height: 100vh; overflow: auto">
  {% if messages %} {% for message in messages %}
  <div
    class="alert alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{%elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}success{% endif %} alert-dismissible fade show"
    role="alert"
  >
    {{ message }}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
  {% endfor %} {% endif %}
  <div class="d-flex align-items-center gap-2">
    <h1 class="text-primary">{{ student.full_name }}</h1>
    -
    <div>
      {% for group in student.groups.all %}<span class="badge text-bg-primary"
        >{{ group.name }}</span
      >
      {% endfor %}
    </div>
  </div>
  <div class="card">
    <div class="d-flex card-header align-items-center justify-content-between">
      <h4>Update student</h4>
      <button
        class="btn btn-link"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#collapseBody"
        aria-expanded="false"
        aria-controls="collapseBody"
      >
        Toggle
      </button>
    </div>
    <div
      id="collapseBody"
      class="collapse"
      aria-labelledby="collapseHeader"
    >
      <div class="card-body">
        <form action="" method="post">
          {% csrf_token %}
          <input type="hidden" name="form_type" value="updzate">
          <div class="row">
            <div
              class="col-lg-6 col-md-12 col-sm-12 mb-2 {% if form.full_name.field.required %}required-field{% endif %}"
            >
              <label for="{{form.full_name.auto_id}}"
                >{{form.full_name.label}}</label
              >
              {{ form.full_name }}
            </div>
            <div
              class="col-lg-6 col-md-12 col-sm-12 mb-2 {% if form.address.field.required %}required-field{% endif %}"
            >
              <label for="{{form.address.auto_id}}"
                >{{ form.address.label }}</label
              >
              {{ form.address }}
            </div>
            <div
              class="col-lg-6 col-md-12 col-sm-12 mb-2 {% if form.address.field.required %}required-field{% endif %}"
            >
              <label for="{{form.groups.auto_id}}"
                >{{ form.groups.label }}</label
              >
              {{ form.groups }}
            </div>
            <div
              class="col-lg-6 col-md-12 col-sm-12 mb-2 {% if form.phone_numbers.field.required %}required-field{% endif %}"
            >
              <label for="{{form.phone_numbers.auto_id}}"
                >{{ form.phone_numbers.label }}</label
              >
              {{ form.phone_numbers }}
            </div>
            <div
              class="col-lg-6 col-md-12 col-sm-12 mb-2 {% if form.course.field.required %}required-field{% endif %}"
            >
              <label for="{{form.course.auto_id}}"
                >{{ form.course.label }}</label
              >
              {{ form.course }}
            </div>
            <div
              class="col-lg-6 col-md-12 col-sm-12 mb-2 {% if form.condition.field.required %}required-field{% endif %}"
            >
              <label for="{{form.condition.auto_id}}"
                >{{ form.condition.label }}</label
              >
              {{ form.condition }}
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
  <div class="mt-5">
    <h3 class="text-secondary">Payment history</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Payment id</th>
          <th scope="col">Date</th>
          <th scope="col">Amount</th>
          <th scope="col">Group</th>
          <th scope="col">Approved</th>
        </tr>
      </thead>
      <tbody>
        {% for payment_info in payments %}
        <tr>
          <th scope="row"> {{ forloop.counter }} </th>
          <td>{{ payment_info.id }}</td>
          <td>{{  payment_info.created_at }}</td>
          <td>{{ payment_info.amount }}UZS</td>
          <td><a href="#">{{ payment_info.assign.class_id.name }}</a></td>
          <td>{{ payment_info.approved }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="card">
    <div class="d-flex card-header align-items-center justify-content-between">
      <h4>Create payment</h4>
      <button
        class="btn btn-link"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#formBody"
        aria-expanded="false"
        aria-controls="formBody"
      >
        Toggle
      </button>
    </div>
    <div
      id="formBody"
      class="collapse show"
      aria-labelledby="collapseHeader"
    >
      <div class="card-body">
       <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="form_type" value="payment">
        {{ payment_form }}
        <button class="btn btn-primary">Create</button>
       </form>
      </div>
    </div>
  </div>
</div>
{% endblock %} {% block script %}
<script>
  document.addEventListener("DOMContentLoaded", () => {
    new Choices("#id_course");
    new Choices("#id_condition");
    new Choices("#id_groups");
    new Choices("#id_assign")
  });
</script>
{% endblock script %}

templates/courses/teachers.html
{% extends "./base.html" %} {% block title %} NANO - O'qituvchilar {% endblock title %} {% block content %}
<div class="container py-3" style="height: 100vh; overflow: auto">
  <div class="row align-items-center">
    {% if messages %} {% for message in messages %}
    <div
      class="alert alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{%elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}success{% endif %} alert-dismissible fade show"
      role="alert"
    >
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endfor %} {% endif %} 
    {% for teacher in teachers %}
    <div class="col-lg-3 col-md-4 col-sm-6">
      <div class="card border-success mb-3" style="max-width: 18rem">
        <div class="card-header bg-transparent border-success">
          {{teacher.get_working_days_display }}, {{teacher.working_time}}
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ teacher.full_name}}</h5>
          {% if teacher.assign_set.all|length %}
          <p class="card-text">
           <b>Guruhlari: </b>
            <span>
              {% for assign in teacher.assign_set.all %}
              <a href="{% url 'courses:group' assign.id %}" class="badge text-bg-primary"
                >{{ assign.class_id }}</a
              >
              {% endfor %}
            </span>
          </p>
          {% else %}
            <p class="text-muted mb-0">Guruhlari yo'q</p>
            {% endif %}
        </div>
        <div class="card-footer bg-transparent border-success d-flex gap-2 flex-wrap">
          <a
            href="{% url 'courses:teacher' teacher.id %}"
            class="btn btn-outline-primary"
            >Batafsil
          </a>
          <form action="{% url 'courses:delete_teacher' teacher.id %}" method="post"> {% csrf_token %} <button class="btn btn-danger" type="submit">Delete</button> </form>
        </div>
      </div>
    </div>
    {% endfor %}
    <div class="col-lg-3 col-md-4 col-sm-6">
      <button
        type="button"
        class="btn btn-outline-secondary"
        data-bs-toggle="modal"
        data-bs-target="#addTeacherModal"
      >
        <div
          class="d-flex justify-content-center align-items-center flex-column"
        >
          <span class="plus-icon" style="font-size: 50px">+</span>
          O'qituvchi qo'shish
        </div>
      </button>
    </div>
  </div>
</div>
<div
  class="modal fade"
  id="addTeacherModal"
  tabindex="-1"
  aria-labelledby="addTeacherModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="addTeacherModalLabel">
          O'qituvchi qo'shish
        </h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <form action="{% url 'courses:teachers' %}" method="post">
      <div class="modal-body">
        {% csrf_token %} {{ form }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Bekor qilish
        </button>
        <button
          type="submit"
          class="btn btn-primary"
          >
          Yaratish
        </button>
      </div>
    </form>
    </div>
  </div>
</div>
{% endblock content %} {% block script %}
<script>
  document.addEventListener("DOMContentLoaded", () => {
    new Choices("#id_courses");
    new Choices("#id_working_days");
  });
</script>
{% endblock %}